require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductcategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Productcategory. As you add validations to Productcategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all productcategories as @productcategories" do
      productcategory = Productcategory.create! valid_attributes
      get :index
      assigns(:productcategories).should eq([productcategory])
    end
  end

  describe "GET show" do
    it "assigns the requested productcategory as @productcategory" do
      productcategory = Productcategory.create! valid_attributes
      get :show, :id => productcategory.id.to_s
      assigns(:productcategory).should eq(productcategory)
    end
  end

  describe "GET new" do
    it "assigns a new productcategory as @productcategory" do
      get :new
      assigns(:productcategory).should be_a_new(Productcategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested productcategory as @productcategory" do
      productcategory = Productcategory.create! valid_attributes
      get :edit, :id => productcategory.id.to_s
      assigns(:productcategory).should eq(productcategory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Productcategory" do
        expect {
          post :create, :productcategory => valid_attributes
        }.to change(Productcategory, :count).by(1)
      end

      it "assigns a newly created productcategory as @productcategory" do
        post :create, :productcategory => valid_attributes
        assigns(:productcategory).should be_a(Productcategory)
        assigns(:productcategory).should be_persisted
      end

      it "redirects to the created productcategory" do
        post :create, :productcategory => valid_attributes
        response.should redirect_to(Productcategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved productcategory as @productcategory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Productcategory.any_instance.stub(:save).and_return(false)
        post :create, :productcategory => {}
        assigns(:productcategory).should be_a_new(Productcategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Productcategory.any_instance.stub(:save).and_return(false)
        post :create, :productcategory => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested productcategory" do
        productcategory = Productcategory.create! valid_attributes
        # Assuming there are no other productcategories in the database, this
        # specifies that the Productcategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Productcategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => productcategory.id, :productcategory => {'these' => 'params'}
      end

      it "assigns the requested productcategory as @productcategory" do
        productcategory = Productcategory.create! valid_attributes
        put :update, :id => productcategory.id, :productcategory => valid_attributes
        assigns(:productcategory).should eq(productcategory)
      end

      it "redirects to the productcategory" do
        productcategory = Productcategory.create! valid_attributes
        put :update, :id => productcategory.id, :productcategory => valid_attributes
        response.should redirect_to(productcategory)
      end
    end

    describe "with invalid params" do
      it "assigns the productcategory as @productcategory" do
        productcategory = Productcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Productcategory.any_instance.stub(:save).and_return(false)
        put :update, :id => productcategory.id.to_s, :productcategory => {}
        assigns(:productcategory).should eq(productcategory)
      end

      it "re-renders the 'edit' template" do
        productcategory = Productcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Productcategory.any_instance.stub(:save).and_return(false)
        put :update, :id => productcategory.id.to_s, :productcategory => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested productcategory" do
      productcategory = Productcategory.create! valid_attributes
      expect {
        delete :destroy, :id => productcategory.id.to_s
      }.to change(Productcategory, :count).by(-1)
    end

    it "redirects to the productcategories list" do
      productcategory = Productcategory.create! valid_attributes
      delete :destroy, :id => productcategory.id.to_s
      response.should redirect_to(productcategories_url)
    end
  end

end
